name: NodeService

services:
  FCJ_auth_service:
    image: FCJ_auth_service:latest
    container_name: FCJ_auth_service
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
