name: typerush-recordservice

services:
  recordservice:
    image: hatohui/recordservice:latest
    build: .
    container_name: recordservice
    ports:
      - '9001:9000'
    restart: always

  recordservice-db:
    image: postgres:17
    container_name: recordservice-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recorddb
    ports:
      - '5433:5432'
    volumes:
      - record_db_data:/var/lib/postgresql/data
      - db:/docker-entrypoint-initdb.d
    restart: always
