name: NodeService

services:
  node-service:
    image: hatohui/node-service:latest
    container_name: node_service
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
